project:
  type: website
  output-dir: docs
  resources:
    - plots/

website:
  title: "California Groundwater Maps"
  sidebar:
    contents:
      - href: index.qmd
        text: Home
      - href: dashboard.qmd
        text: Dashboard
      - href: TNCMap.qmd
        text: TNC Sites

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



