project:
  type: website
  output-dir: docs
  resources:
    - plots/

website:
  title: "CNRA_map"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: dashboard.qmd
      - text: Dashboard
      - href: TNC Sites
      - text: TNCMap.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



